### PR TITLE
Add missing dep for vignette

### PR DESCRIPTION
**Pull request by maelle**
Cf https://github.com/r-universe/ropensci/runs/4485274916?check_suite_focus=true via https://ropensci.r-universe.dev/ui#builds

### CODE REVIEW

**Comment by maelle** [comment]
You might also want to add https://github.com/ropensci/NLMR/blob/f285a9ec17cf3346b9251f80feabec2cb1a1abb2/_pkgdown.yml#L49 to DESCRIPTION under Suggests actually :thinking:

**Comment by maelle** [comment]
Now, if the deps are just for the website, you can use "Config/needs/website" instead of Suggests.

**Comment by marcosci** [comment]
Hi Maelle,

thanks for spotting this - but what exactly is Config/needs/website? 👯 
I found it in pak, but ... can I somehow put this in the description?

Cheers

**Comment by maelle** [comment]
Sooo `Config/needs/website` is only for packages needed for the website but not R CMD check (e.g. packages used in a non-vignette article, packages needed for better autolinking by downlit e.g. if you mention an usethis function somewhere). 

Now it's not supported just yet by the docs building system cf https://github.com/r-universe-org/build-docs/pull/1 so my suggestion was a bit too early.

**Comment by maelle** [comment]
@marcosci I see this updated chapter https://r-pkgs.org/description.html of the R packages book has info on the Config/needs fields!

**Comment by jeroen** [comment]
Let's give this a try to get the new docs online -- we can tweak it more later.

**Pull request merged**
